# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 13:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_auto_20170601_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='subscription_type',
            field=models.CharField(blank=True, choices=[(b'b', b'7,000'), (b'i', b'12,000'), (b'p', b'25,000')], help_text='Enter the subscription plan for the user (e.g. basic,  etc.)', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
