# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('description', models.TextField(max_length=1000)),
                ('feed_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='died')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the book', max_length=7000)),
                ('isbn', models.CharField(blank=True, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, null=True, verbose_name='ISBN')),
                ('publisher', models.CharField(help_text='Enter the publisher of the book', max_length=300, null=True)),
                ('language', models.CharField(choices=[(b'c', b'Chinese'), (b'e', b'English'), (b's', b'Spanish'), (b'f', b'French'), (b'g', b'german'), (b'h', b'hindi'), (b'i', b'italian')], help_text="select a the book's natural language (e.g. English, French, Japanese etc.)", max_length=1)),
                ('upload', models.FileField(null=True, upload_to='uploads/pdf')),
                ('image', models.ImageField(null=True, upload_to='uploads/img')),
                ('imprint', models.CharField(max_length=200)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[(b'd', b'Maintenance'), (b'o', b'On loan'), (b'a', b'Available'), (b'r', b'Reserved')], default='d', help_text='Book availability', max_length=1)),
                ('price', models.IntegerField(default=0)),
                ('discount_price', models.IntegerField(default=0, null=True)),
                ('author', models.ManyToManyField(to='catalog.Author')),
            ],
            options={
                'ordering': ['due_back'],
                'permissions': (('can_mark_returned', 'Set book as returned'),),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(b's', b'Science fiction'), (b'd', b'Drama'), (b'a', b'Action'), (b'r', b'Romance'), (b'm', b'Mystery'), (b'ho', b'Horror'), (b'he', b'Health'), (b'ar', b'Art'), (b'hi', b'History'), (b'ma', b'Math'), (b'p', b'Poetry'), (b'e', b'Encyclopedias'), (b'd', b'Dictionaries')], help_text='Enter a book genre (e.g. Science Fiction, French Poetry etc.)', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'verbose_name_plural': 'ID',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='catalog.Genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='key',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Id', verbose_name='User E ID'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Author'),
        ),
    ]
