# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170605_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Book ID'),
        ),
        migrations.DeleteModel(
            name='Id',
        ),
    ]
